### ISSUE TITLE
release please

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/ccf-widget#28]
@thewtex the currently released version is out-of-date due to changes to fsspec and importlib-metadata. The necessary pins have been made in the pyproject.toml file. Could you please push a release so we can use it in nwbwidgets?

**Comment by thewtex** [comment]
@bendichter :+1: yes, will do

**Comment by thewtex** [comment]
Released 0.5.3: https://pypi.org/project/ccfwidget/0.5.3/

@bendichter PyPI invite also sent

itkwidgets currently undergoing a major update -- will upstream here once stable
