### ISSUE TITLE
inconsistent behavior when setting `selected_allen_ids`

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/ccf-widget#3]
![image](https://user-images.githubusercontent.com/844306/84602173-64824900-ae53-11ea-8d20-0d785bce79ca.png)

**Comment by thewtex** [comment]
I think I reproduced this the behavior was not presenting consistently. https://github.com/NeurodataWithoutBorders/ccf-widget/pull/1/commits/107dd5f2eeee90237423cd04a7f292a8cd559313 intends to address. Do you still observe this behavior with this patch?

**Comment by bendichter** [comment]
@thewtex yeah, that worked

**Comment by brianhhu** [comment]
I'm still seeing inconsistent behavior on the master branch. For example, this fails for me:

```python
structures = ['VISp' , 'VISl', 'VISal', 'VISrl', 'VISpm', 'VISam', 'LGd', 'LP']
ccf.selected_acronyms = structures

print(ccf.selected_acronyms)  # Either shows ['VISp'] or []
```

It also fails using the corresponding selected_allen_ids. It seems things are temporarily selected (I see them flash in the ipytree), but don't stick.

**Comment by thewtex** [comment]
We were a little #extra with the trait sync'ing -- #6 will make it stable.
