### ISSUE TITLE
Combine label maps for a given visual area

### ISSUE THREAD

**Issue by brianhhu** [NeurodataWithoutBorders/ccf-widget#7]
Currently, selecting an area from ipytree selects all leafs as well (e.g. selecting 'Primary visual area' selects layers 1-6). This renders each layer a different color, when it may be more meaningful to render all layers for a given visual area in the same color.

**Comment by thewtex** [comment]
@brianhhu good idea. Yes, and we'll see if we can use the official Allen colors for structures.

**Comment by thewtex** [comment]
Surface meshes are added with the official Allen structure colors.
